apiVersion: v2
appVersion: 1.1.1
description: Kubernetes native operator which fully manages Jenkins on Kubernetes
name: jenkins-operator
version: 4.2.0
icon: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/assets/jenkins-operator-icon.png
dependencies:
- name: cert-manager
  version: "1.5.1"
  condition: webhook.enabled
  repository: https://charts.jetstack.io